### ISSUE TITLE
Compile error in current HEAD

### ISSUE THREAD

**Issue by mathiasertl** [processone/xml#15]
When currently compiling the library, I get the following error:

```
c_src/xml_stream.o: In function `nif_init':
/tmp/buildd/erlang-p1-xml-0.2015.10.01/c_src/xml_stream.c:626: multiple definition of `nif_init'
c_src/xml.o:/tmp/buildd/erlang-p1-xml-0.2015.10.01/c_src/xml.c:298: first defined here
ERROR: sh(cc c_src/xml.o c_src/xml_stream.o -fPIE -pie -Wl,-z,relro -Wl,-z,now  -shared  -L"/usr/lib/erlang/lib/erl_interface-3.8/lib" -lerl_interface -lei -o priv/p1_xml_drv.so)
failed with return code 1 and the following output:
c_src/xml_stream.o: In function `nif_init':
/tmp/buildd/erlang-p1-xml-0.2015.10.01/c_src/xml_stream.c:626: multiple definition of `nif_init'
c_src/xml.o:/tmp/buildd/erlang-p1-xml-0.2015.10.01/c_src/xml.c:298: first defined here
collect2: error: ld returned 1 exit status
```

Any idea what the problem could be? I tried compiling on both Debian Jessie and Debian Unstable and get the same error.

**Comment by mathiasertl** [comment]
I have been able to cut down the issue somewhat: The error first occurs in c1e5f4937152bf6a72569921962c544a56ea95dd, it works in the commit before that.

Also, the issue is annoyingly hard to reproduce. @weiss is not having this _at all_. I'm having this issue when building an updated version of the official Debian package (in a pbuilder chroot). And only when building with git-buildpackage. When I log into the chroot and execute `debian/rules build` the package builds just fine.

**Comment by debalance** [comment]
I use git-buildpackage with a pbuilder chroot all the time and don't have this problem with the latest commit on Debian unstable.

**Comment by zinid** [comment]
This line looks really suspicious:
```
cc c_src/xml.o c_src/xml_stream.o -fPIE -pie -Wl,-z,relro -Wl,-z,now  -shared  -L"/usr/lib/erlang/lib/erl_interface-3.8/lib" -lerl_interface -lei -o priv/p1_xml_drv.so
```
`p1_xml_drv.so` should not even be compiled. Also, the problem occurs because `xml.o` and `xml_stream.o` are linked together as they have the same function `nif_init`.

I'm wondered why that line is generated, I don't have it when compiling on my machine.

**Comment by debalance** [comment]
@mathiasertl : try my latest packaged version from
https://anonscm.debian.org/cgit/users/debalance/erlang-p1-xml.git/

I don't get the line @zinid mentioned in my build logs either.

**Comment by mathiasertl** [comment]
@debalance thanks for the link to your repo, your packages didn't have the VCS-* fields at first. 

I synchronized my package with yours, and compilation now seems to work fine. HOWEVER, now the eunit tests fail:

```
module 'xml_test'
  xml_test: start_test...
=WARNING REPORT==== 4-Oct-2015::09:56:03 ===
unable to load xml NIF: {error,
                            {load_failed,
                                "Failed to load NIF library: './priv/lib/xml.so: cannot open shared object file: No such file or directory'"}}

=ERROR REPORT==== 4-Oct-2015::09:56:03 ===
failed to load NIF ./priv/lib/xml_stream: Failed to load NIF library: './priv/lib/xml_stream.so: cannot open shared object file: No such file or directory'
=INFO REPORT==== 4-Oct-2015::09:56:03 ===  
    application: p1_xml
    exited: {unable_to_load_nif,{xml_app,start,[normal,[]]}}
    type: temporary
*failed*
```

My package now has no relevant difference (except for changelog, lintian overrides etc) to @debalance's package. The package is btw here: https://github.com/jabber-at/xml

**Comment by debalance** [comment]
@mathiasertl , I have already opened #16 for that, so I guess you can mark this issue as resolved.

You can disable the eunit tests by removing "eunit" from debian/dh-rebar.conf.

**Comment by mathiasertl** [comment]
Ah, indeed so. Thanks for the support everyone, I will monitor the other issue.
