### ISSUE TITLE
tests fail to load *.so

### ISSUE THREAD

**Issue by debalance** [processone/xml#16]
Hi,

with the latest commit I can't use "rebar eunit" while building the debian package anymore because it fails to load the *.so files:

Failed to load NIF library: './priv/lib/xml.so: cannot open shared object file: No such file or directory

It's definitely there:
debalance@emmagan:/debian/main/erlang-p1-xml$ find . -name *.so
./priv/lib/xml_stream.so
./priv/lib/xml.so

Any ideas how to fix that?

Since github fails to process the build log, I have put it here:
https://people.debian.org/~debalance/build-logs/erlang-p1-xml_0.2015.10.01-1_amd64.build

If I skip the tests, the package building process completes and installes the *.so files correctly.

**Comment by prefiks** [comment]
Hello, i seen this too, this is result of "wrong" directory name where you have your lib. Our code for locating .so files (https://github.com/processone/xml/blob/master/src/xml.erl#L408) uses `code:priv_dir()`, it requires that application must be placed in directory named after application id. We also have fallback code when `code:priv_dir` fails, but `filename:dirname()` that we use, returns relative paths, and they don't work correctly with `rebar eunit` that modifies current dir.

**Comment by prefiks** [comment]
I thin this should be fixed in 455a567e4046399169c494e0900e3aa73bba856b, please reopen if this would still not fix this problem for you.

**Comment by theju** [comment]
I am afraid, this commit may not have fixed it. The `erlang:load_nif/2` function seems to be getting a `none` from the `xml:get_so_path/2` function. Maybe it's not picking up the path to the `xml_stream.so` and `xml.so` files correctly?

Here's the error:

```
2015-10-05 10:34:23.803 [error] <0.111.0> CRASH REPORT Process <0.111.0> with 0 neighbours exited with reason: bad argument in call to erlang:load_nif(none, 0) in xml_stream:load_nif/0 line 56 in application_master:init/4 line 134
2015-10-05 10:34:23.807 [critical] <0.39.0>@ejabberd:exit_or_halt:133 failed to start application 'p1_xml': {error,
                                       {bad_return,
                                        {{xml_app,start,[normal,[]]},
                                         {'EXIT',
                                          {badarg,
                                           [{erlang,load_nif,[none,0],[]},
                                            {xml_stream,load_nif,0,
                                             [{file,"src/xml_stream.erl"},
                                              {line,56}]},
                                            {xml_app,start,2,
                                             [{file,"src/xml_app.erl"},
                                              {line,52}]},
                                            {application_master,start_it_old,
                                             4,
                                             [{file,"application_master.erl"},
                                              {line,273}]}]}}}}}

```

I am using OTP 18 and ejabberd from the current HEAD of master branch and following the standard `./configure && make && sudo make install`

The above error arises during `sudo ejabberdctl start`

**Comment by debalance** [comment]
For me it has solved the problem, all tests pass with "rebar eunit" and p1_xml is successfully loaded with both ejabberd 15.03 and 15.09.

**Comment by theju** [comment]
On Ubuntu 14.04, here are the steps I am using to build Ejabberd-15.09 on top of otp 18.1:

```
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install autoconf libexpat-dev libyaml-dev libssl-dev make ncurses-dev git-core g++
wget http://www.erlang.org/download/otp_src_18.1.tar.gz
tar xvf otp_src_18.1.tar.gz
cd otp_18.1.tar.gz
./configure && make && sudo make install
cd
wget https://github.com/processone/ejabberd/archive/15.09.tar.gz
tar xvf 15.09.tar.gz
cd ejabberd-15.09
./autogen.sh
./configure --prefix=/usr/local && make && sudo make install
sudo ejabberdctl start
sudo tail -n 30 -f /usr/local/var/log/ejabberd/error.log
```

The error is

```
2015-10-06 03:31:44.536 [error] <0.111.0> CRASH REPORT Process <0.111.0> with 0 neighbours exited with reason: bad argument in call to erlang:load_nif(none, 0) in xml_stream:load_nif/0 line 56 in application_master:init/4 line 134
2015-10-06 03:31:44.542 [critical] <0.39.0>@ejabberd:exit_or_halt:133 failed to start application 'p1_xml': {error,
                                       {bad_return,
                                        {{xml_app,start,[normal,[]]},
                                         {'EXIT',
                                          {badarg,
                                           [{erlang,load_nif,[none,0],[]},
                                            {xml_stream,load_nif,0,
                                             [{file,"src/xml_stream.erl"},
                                              {line,56}]},
                                            {xml_app,start,2,
                                             [{file,"src/xml_app.erl"},
                                              {line,52}]},
                                            {application_master,start_it_old,
                                             4,
                                             [{file,"application_master.erl"},
                                              {line,273}]}]}}}}}
```

I repeated the process with Otp 17.5.3 and same results.

Here are the results of the `rebar eunit` in my case:

```
Failed: 4.  Skipped: 0.  Passed: 210.
Cover analysis: /home/ubuntu/ejabberd-15.09/deps/lager/.eunit/index.html
ERROR: One or more eunit tests failed.
ERROR: eunit failed while processing /home/ubuntu/ejabberd-15.09/deps/lager: rebar_abort
```

@debalance Can you please have a look if something is obviously wrong? Or better if you can share your steps?

**Comment by prefiks** [comment]
I tried to make code for locating those .so more bulletproof, ./rebar update-deps should grab updated version for you.

If you would like to use ejabberd-15.09 with all dependences pointing to commits, that we were testing, instead of newest version from git, please download source code from https://www.process-one.net/en/ejabberd/downloads/, instead from git

**Comment by debalance** [comment]
@theju, I don't see anything obviously wrong, but I neither build erlang nor ejabberd directly from source as you do, I use packaged versions on Debian Sid.
This means I install the erlang packages, build all the deps of ejabberd as separate packages and finally build the ejabberd package where I patched out the part that downloads and builds the deps.

The packaging process automates a lot, like including the default buildflags for your distribution+release and using the right directories.

All the packages are built with git-buildpackage and are available from the Debian Archive and here:
https://anonscm.debian.org/cgit/users/debalance/

Mathias Ertl has (back)ported my work to Ubuntu and provides a custom repository here:
https://jabber.at/en/apt-repository

**Comment by theju** [comment]
@prefiks Thanks for the pointer and ejabberd starts fine when compiled without any flags. It was not obvious to me that the GH downloaded rebar config script did not have the dependencies pinned down to commits. But on the other hand, I've run into issues when redis and elixir plugins are enabled and commits not being found (will post to the ejabberd issue tracker).

@debalance Thanks for your patience in helping me out.

**Comment by mathiasertl** [comment]
So all current issues are resolved for everyone? Can I deploy? ^^

**Comment by theju** [comment]
@mathiasertl Yes.
