### ISSUE TITLE
xml_test: many_stream_elements_test fails on some architectures

### ISSUE THREAD

**Issue by debalance** [processone/xml#17]
Hi,

if you look at https://buildd.debian.org/status/package.php?p=erlang-p1-xml&suite=sid you see that the build fails on several architectures, you can access the logs by clicking on "Build-Attempted".

The lower grey half can be ignored, those are unofficial ports, but the upper white half are Debian Release architectures.

In every case, there's the same failing test responsible:

  xml_test: many_stream_elements_test...*timed out*
undefined
 =======================================================
  Failed: 0.  Skipped: 0.  Passed: 30.
One or more tests were cancelled.

I have access to porter-boxes for every architecture and can test patches if you provide them.
Note that the failing architectures have most likely less computing power than the others.

**Comment by zinid** [comment]
This is now fixed in da15119a4224ff94211261e5f38255f5e7a42492
