### ISSUE TITLE
is it still true that "Description  This xml module is for compatibility with ejabberd." as in the link from your site?

### ISSUE THREAD

**Issue by edwardt** [processone/xml#2]
It does look like exmpp and xml are not related in terms of the development path under github checkin  history found in github  other than they both deal with xml stanza parsing ....

link: 
http://www.process-one.net/docs/exmpp/devdoc/trunk/xml.html
If not, can you correct the doc?

Thanks

**Comment by mremond** [comment]
p1_xml supercedes and obsoletes exmpp. We focus on this smaller low level module (p1_xml)
