### ISSUE TITLE
empty string decoded as atom undefined

### ISSUE THREAD

**Issue by vesvalo** [processone/xml#6]
xmlrpc_codec decodes `<string/>` to atom **undefined**:
`decode_string_cdata(__TopXMLNS, <<>>) -> undefined;`

We are using ejabberd-contrib/mod_admin_extra:add_rosteritem, and if we pass empty string to xmlrpc, we get the following error:
Error: the command "add_rosteritem" requires 1 more argument.

Please change the code this way:
`decode_string_cdata(__TopXMLNS, <<>>) -> <<>>;`

**Comment by mremond** [comment]
Thanks, we will have a look :+1:

**Comment by zinid** [comment]
The issue is fixed in 98444ecea063ac55751667c198c438ab4cf63275
